-- Generated from DBF schemas
-- Generated on: 2025-08-19 21:45:22
-- Total tables: 1

-- Generated from DBF schema
-- Table: STOC
-- Last Updated: 2025-08-19
-- Record Count: 239619

CREATE TABLE STOC (
    DUBLU BOOLEAN,
    DATA DATE,
    CATEGORIE VARCHAR(15),
    DENUMIRE VARCHAR(40),
    CANTITATE DECIMAL(12,3),
    CANT_REZER DECIMAL(12,3),
    MOSTRE DECIMAL(10,3),
    UNIT_MAS VARCHAR(6),
    PRET DECIMAL(17,4),
    PRET_ACHI DECIMAL(17,4),
    GARANTIE DATE,
    COD INTEGER,
    LA_ENGROS VARCHAR(1),
    OBSERVATII VARCHAR(40),
    DEPOZITUL INTEGER,
    BUC VARCHAR(6),
    PROTVAACHI DECIMAL(4,1),
    PROTVAVINZ DECIMAL(4,1),
    COD_CORESP INTEGER,
    FURNIZOR INTEGER,
    COD_BARE VARCHAR(20),
    ADRESA VARCHAR(10),
    PRO_VAMA DECIMAL(6,2),
    PRET_B DECIMAL(16,2),
    PRET_C DECIMAL(16,2),
    SHORT_C VARCHAR(5),
    COD_CUTIE VARCHAR(20),
    PRET_RECEP DECIMAL(16,2),
    PROL DECIMAL(17,4),
    PROL_ACHI DECIMAL(17,4),
    KILOGRAME DECIMAL(9,3),
    GABARIT VARCHAR(16),
    CHEIECMD VARCHAR(20),
    LOT VARCHAR(30),
    CODTXINV VARCHAR(6),
    CODVAMAL VARCHAR(8),
    CODCPV VARCHAR(10),
    KILO_NET DECIMAL(9,3)
);

-- Indexes from MDX file
CREATE INDEX idx_STOC_ ON STOC ();
CREATE INDEX idx_STOC_t ON STOC (t);
CREATE INDEX idx_STOC_? ON STOC (?);
CREATE INDEX idx_STOC_? ON STOC (?);
CREATE INDEX idx_STOC_?  ON STOC (? );
CREATE INDEX idx_STOC_" ON STOC (");
CREATE INDEX idx_STOC_4" ON STOC (4");


